# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('country', models.ManyToManyField(blank=True, to='administration.Country')),
                ('currency', models.ManyToManyField(blank=True, to='administration.Currency')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.ManyToManyField(to='administration.AccessLevel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('command_function', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('reverse_function', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=100)),
                ('service_account', models.CharField(blank=True, max_length=45, null=True)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('node_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NodeSystem')),
                ('payment_method', models.ManyToManyField(blank=True, to='bridge.PaymentMethod')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.CommandStatus')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('request', models.CharField(max_length=12800)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('raise_charges', models.NullBooleanField(default=False)),
                ('response', models.CharField(blank=True, max_length=3840, null=True)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Channel')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge', to='administration.Currency')),
                ('current_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction__current_command', to='bridge.ServiceCommand')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway')),
                ('gateway_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('msisdn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.MSISDN')),
                ('next_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction__next_command', to='bridge.ServiceCommand')),
                ('overall_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge__transaction__overall_status', to='administration.ResponseStatus')),
                ('response_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Service')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.TransactionStatus'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.ServiceStatus'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.PaymentMethodStatus'),
        ),
    ]
