# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecommand',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='administration.Gateway'),
        ),
    ]
