# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_servicecommand_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='receive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
