# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_mno_mnoprefix'),
        ('bridge', '0003_auto_20160627_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecommand',
            name='channel',
            field=models.ManyToManyField(blank=True, to='administration.Channel'),
        ),
    ]
