# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('bridge', '0004_auto_20170717_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundserviceactivity',
            old_name='details',
            new_name='request',
        ),
        migrations.AddField(
            model_name='backgroundservice',
            name='details',
            field=models.CharField(default=b'{}', max_length=1920),
        ),
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='response_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_current_command', to='bridge.ServiceCommand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='next_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_next_command', to='bridge.ServiceCommand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='overall_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_transaction_overall_status', to='administration.ResponseStatus'),
        ),
    ]
