# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_mno_mnoprefix'),
        ('bridge', '0004_servicecommand_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='channel',
            field=models.ManyToManyField(blank=True, to='administration.Channel'),
        ),
    ]
