# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_paymentmethod_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True),
        ),
    ]
