# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0024_auto_20170519_1205'),
        ('bridge', '0008_auto_20170523_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecommand',
            name='profile_status',
            field=models.ManyToManyField(blank=True, to='upc.ProfileStatus'),
        ),
    ]
