# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0009_servicecommand_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='csrf_token',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True),
        ),
    ]
