# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20170614_1816'),
        ('bridge', '0010_transaction_csrf_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='default_currency',
            field=models.ForeignKey(default=74, on_delete=django.db.models.deletion.CASCADE, related_name='default_currency', to='administration.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
