# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='updated',
            field=models.SmallIntegerField(default=0, help_text=b'1 for record that is not the last record'),
        ),
    ]
