# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0002_accountmanager_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmanager',
            name='updated',
        ),
    ]
