# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0003_remove_accountmanager_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='updated',
            field=models.BooleanField(default=False, help_text=b'True for record that is not the last record'),
        ),
    ]
