# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170917_0819'),
        ('upc', '0001_initial'),
        ('vbs', '0004_accountmanager_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.NullBooleanField(default=False)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('account_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionTill')),
                ('account_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountStatus')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType')),
                ('credit_limit_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAccountManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
                ('transaction_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_bf', models.DecimalField(decimal_places=2, max_digits=19)),
                ('updated', models.BooleanField(default=False, help_text=b'True for record that is not the last record')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Profile'),
        ),
        migrations.AddField(
            model_name='institutionaccountmanager',
            name='dest_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_dest_account', to='vbs.Account'),
        ),
        migrations.AddField(
            model_name='institutionaccountmanager',
            name='source_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.Account'),
        ),
    ]
