# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0005_auto_20171003_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='gateway_profile',
        ),
    ]
