# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('base', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=1024)),
                ('expiry', models.DateTimeField()),
                ('visits', models.IntegerField()),
                ('updated', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('gateway_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ShortenerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='URLType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('updated', models.BooleanField(default=False)),
                ('max_visits', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shortener',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gus.ShortenerStatus'),
        ),
        migrations.AddField(
            model_name='shortener',
            name='url_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gus.URLType'),
        ),
    ]
