# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_mno_mnoprefix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tier',
        ),
        migrations.AddField(
            model_name='gateway',
            name='default_host',
            field=models.ManyToManyField(blank=True, to='administration.Host'),
        ),
    ]
