# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_industryclass_industrydivision_industrygroup_industrysection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryclass',
            name='group_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='industrydivision',
            name='section_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='industrygroup',
            name='division_code',
            field=models.CharField(max_length=5),
        ),
    ]
