# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 10:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20160919_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryclass',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 10, 23, 2, 881252, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryclass',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 10, 23, 13, 401008, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industryclass',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.IndustryGroup'),
        ),
        migrations.AddField(
            model_name='industrydivision',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 10, 23, 21, 894167, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrydivision',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 10, 23, 30, 507276, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrydivision',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.IndustrySection'),
        ),
        migrations.AddField(
            model_name='industrygroup',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 10, 23, 37, 178401, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrygroup',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 10, 23, 45, 555684, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrygroup',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.IndustryDivision'),
        ),
        migrations.AddField(
            model_name='industrysection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 10, 23, 52, 522140, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industrysection',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 10, 23, 58, 407477, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
