# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20160919_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
