# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-02 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='theme',
        ),
    ]
