# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='accent_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='primary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
