# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-02 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20170306_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('buying', models.DecimalField(decimal_places=2, max_digits=19)),
                ('selling', models.DecimalField(decimal_places=2, max_digits=19)),
                ('trading_date', models.DateField(default=datetime.date(2017, 6, 2))),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
            ],
        ),
    ]
