# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-14 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_forex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forex',
            old_name='from_currency',
            new_name='base_currency',
        ),
        migrations.RenameField(
            model_name='forex',
            old_name='buying',
            new_name='exchange_rate',
        ),
        migrations.RenameField(
            model_name='forex',
            old_name='to_currency',
            new_name='quote_currency',
        ),
        migrations.RemoveField(
            model_name='forex',
            name='selling',
        ),
    ]
