# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
        ('crm', '0001_initial'),
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('validate_min', models.CharField(max_length=45)),
                ('validate_max', models.CharField(max_length=45)),
                ('default_value', models.CharField(blank=True, max_length=600, null=True)),
                ('variable_kind', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=45, null=True)),
                ('item_level', models.IntegerField()),
                ('access_level', models.ManyToManyField(to='administration.AccessLevel')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('item_level', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=45, null=True)),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='PageInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('page_input', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=45, null=True)),
                ('section_size', models.CharField(blank=True, max_length=45, null=True)),
                ('item_level', models.CharField(max_length=4)),
                ('access_level', models.ManyToManyField(to='administration.AccessLevel')),
                ('channel', models.ManyToManyField(to='administration.Channel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Profile')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('input_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.InputVariable')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
                ('page', models.ManyToManyField(to='iic.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PageInputGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('icon', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(max_length=200)),
                ('item_level', models.CharField(max_length=4)),
                ('section', models.CharField(max_length=45)),
                ('section_size', models.CharField(max_length=45)),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('input_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.InputVariable')),
            ],
        ),
        migrations.CreateModel(
            name='PageInputStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('variable', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pageinput',
            name='page_input_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.PageInputGroup'),
        ),
        migrations.AddField(
            model_name='pageinput',
            name='page_input_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.PageInputStatus'),
        ),
        migrations.AddField(
            model_name='pageinput',
            name='product_type',
            field=models.ManyToManyField(blank=True, to='crm.ProductType'),
        ),
        migrations.AddField(
            model_name='pageinput',
            name='trigger',
            field=models.ManyToManyField(blank=True, to='iic.Trigger'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.PageGroup'),
        ),
        migrations.AddField(
            model_name='page',
            name='service',
            field=models.ManyToManyField(blank=True, to='bridge.Service'),
        ),
        migrations.AddField(
            model_name='inputvariable',
            name='variable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.VariableType'),
        ),
    ]
