# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
        ('iic', '0002_remove_pageinput_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinput',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
    ]
