# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0003_pageinput_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinputgroup',
            name='auto_submit',
            field=models.BooleanField(default=False),
        ),
    ]
