# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0003_auto_20170717_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageinputgroup',
            old_name='section',
            new_name='style',
        ),
    ]
