# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0004_pageinputgroup_auto_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputvariable',
            name='default_value',
            field=models.CharField(blank=True, max_length=12800, null=True),
        ),
    ]
