# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0005_auto_20160822_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinputgroup',
            name='section_height',
            field=models.IntegerField(default=900),
            preserve_default=False,
        ),
    ]
