# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0006_pageinputgroup_section_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinput',
            name='f_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iic.Page'),
        ),
        migrations.AlterField(
            model_name='pageinput',
            name='page',
            field=models.ManyToManyField(related_name='pageinput__page', to='iic.Page'),
        ),
    ]
