# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0007_auto_20170227_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinput',
            name='f_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_page', to='iic.Page'),
        ),
        migrations.AlterField(
            model_name='pageinput',
            name='page',
            field=models.ManyToManyField(to='iic.Page'),
        ),
    ]
