# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0009_auto_20170227_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinput',
            name='page',
        ),
    ]
