# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0010_remove_pageinput_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinput',
            name='f_page',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='iic.Page'),
        ),
    ]
