# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0011_auto_20170227_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageinput',
            old_name='f_page',
            new_name='page',
        ),
    ]
