# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0012_auto_20170227_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinput',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iic.Page'),
        ),
    ]
