# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-16 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0014_pageinput_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='access_level',
            field=models.ManyToManyField(blank=True, to='administration.AccessLevel'),
        ),
        migrations.AlterField(
            model_name='pageinput',
            name='access_level',
            field=models.ManyToManyField(blank=True, to='administration.AccessLevel'),
        ),
    ]
