# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-16 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0022_auto_20170426_1956'),
        ('iic', '0015_auto_20170516_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='profile_status',
            field=models.ManyToManyField(blank=True, to='upc.ProfileStatus'),
        ),
    ]
