# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0008_auto_20170523_1741'),
        ('iic', '0016_page_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinput',
            name='bridge_trigger',
            field=models.ManyToManyField(blank=True, to='bridge.Trigger'),
        ),
    ]
