# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-23 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0017_pageinput_bridge_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinput',
            name='trigger',
        ),
    ]
