# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-23 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0019_auto_20170523_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
