# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20170707_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecontact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salecontact_created_by', to='upc.GatewayProfile'),
        ),
    ]
