# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinput',
            name='style',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
