# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0002_pageinput_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinputgroup',
            name='section',
            field=models.TextField(),
        ),
    ]
