# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0004_auto_20170717_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinput',
            name='style',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pageinputgroup',
            name='style',
            field=models.TextField(blank=True),
        ),
    ]
