# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccountManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
                ('transaction_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_bf', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dest_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_account', to='loyalty.LoyaltyAccount')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.LoyaltyAccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('point_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionTill')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='account_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.LoyaltyAccountStatus'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.LoyaltyAccountType'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account__created_by', to='upc.GatewayProfile'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='gateway_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
        ),
    ]
