# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account_created_by', to='upc.GatewayProfile'),
        ),
    ]
