# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('data_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=640, null=True)),
                ('content', models.CharField(blank=True, max_length=2560, null=True)),
                ('is_function', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('channel', models.ManyToManyField(blank=True, to='administration.Channel')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='DataListGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataListStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('processing_path', models.CharField(max_length=45)),
                ('quuery', models.CharField(blank=True, max_length=1280, null=True)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reporting',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.ReportingStatus'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsc.DataListGroup'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='institution',
            field=models.ManyToManyField(blank=True, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.DataListStatus'),
        ),
    ]
