# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('data_name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=640, null=True)),
                ('content', models.CharField(blank=True, max_length=2560, null=True)),
                ('is_report', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('data_response', models.BooleanField(default=False)),
                ('pn_data', models.BooleanField(default=False, help_text=b'Push Notification', verbose_name=b'Push Notification')),
                ('pn_id_field', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Push Notification ID Field')),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('channel', models.ManyToManyField(blank=True, to='administration.Channel')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='DataListGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataListQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=100)),
                ('values', models.CharField(blank=True, max_length=512, null=True)),
                ('or_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('and_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('module_name', models.CharField(max_length=100)),
                ('institution_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('gateway_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('order', models.CharField(blank=True, max_length=512, null=True)),
                ('count_values', models.CharField(blank=True, max_length=512, null=True)),
                ('filters', models.CharField(blank=True, max_length=512, null=True)),
                ('date_values', models.CharField(blank=True, max_length=512, null=True)),
                ('date_time_values', models.CharField(blank=True, max_length=512, null=True)),
                ('links', models.CharField(blank=True, max_length=512, null=True)),
                ('link_params', models.CharField(blank=True, max_length=512, null=True)),
                ('list_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('data_response', models.BooleanField(default=False)),
                ('sum_values', models.CharField(blank=True, max_length=512, null=True)),
                ('not_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('last_balance', models.CharField(blank=True, max_length=512, null=True)),
                ('gateway_profile_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('month_year_values', models.CharField(blank=True, max_length=512, null=True)),
                ('avg_values', models.CharField(blank=True, max_length=512, null=True)),
                ('date_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('time_filters', models.CharField(blank=True, max_length=512, null=True)),
                ('token_filter', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataListStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('activity_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsc__fileupload__activity_service', to='bridge.Service')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
                ('trigger_service', models.ManyToManyField(to='bridge.Service')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.FileField(blank=True, max_length=200, null=True, upload_to=b'dsc_fileuploadactivity/')),
                ('processed_file_path', models.FileField(blank=True, max_length=200, null=True, upload_to=b'dsc_fileuploadactivity/')),
                ('details', models.CharField(max_length=1920)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Channel')),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.FileUpload')),
                ('gateway_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(max_length=200, upload_to=b'dsc_imagelist_image/')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('level', models.IntegerField(default=0)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('channel', models.ManyToManyField(blank=True, to='administration.Channel')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='ImageListType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='imagelist',
            name='image_list_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.ImageListType'),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='institution',
            field=models.ManyToManyField(blank=True, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='fileuploadactivity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.FileUploadActivityStatus'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsc.DataListGroup'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='institution',
            field=models.ManyToManyField(blank=True, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsc.DataListQuery'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.DataListStatus'),
        ),
    ]
