# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0004_auto_20160528_0459'),
        ('bridge', '0001_initial'),
        ('dsc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('activity_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsc__fileupload__activity_service', to='bridge.Service')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
                ('trigger_service', models.ManyToManyField(to='bridge.Service')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('file_path', models.FileField(blank=True, max_length=200, null=True, upload_to=b'dsc_fileuploadactivity/')),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.FileUpload')),
            ],
        ),
        migrations.RenameField(
            model_name='reporting',
            old_name='quuery',
            new_name='query',
        ),
    ]
