# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0002_auto_20160609_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadactivity',
            name='tmp_file_path',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'tmp/uploads/'),
        ),
    ]
