# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0004_auto_20160528_0459'),
        ('dsc', '0003_fileuploadactivity_tmp_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='fileuploadactivity',
            name='gateway_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileuploadactivity',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileuploadactivity',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='fileuploadactivity',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dsc.FileUploadActivityStatus'),
            preserve_default=False,
        ),
    ]
