# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0005_datalist_pn_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='activity_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsc_fileupload_activity_service', to='bridge.Service'),
        ),
    ]
