# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0005_auto_20160613_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadactivity',
            name='details',
            field=models.CharField(default={}, max_length=1920),
            preserve_default=False,
        ),
    ]
