# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0006_fileuploadactivity_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
