# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-21 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_mno_mnoprefix'),
        ('dsc', '0007_datalist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadactivity',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Channel'),
            preserve_default=False,
        ),
    ]
