# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0008_fileuploadactivity_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalist',
            old_name='is_function',
            new_name='is_report',
        ),
        migrations.RemoveField(
            model_name='datalist',
            name='title',
        ),
        migrations.AddField(
            model_name='datalist',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
