# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0009_auto_20160827_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
