# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0011_auto_20160827_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalistquery',
            name='gateway_profile_filter',
        ),
        migrations.RemoveField(
            model_name='datalistquery',
            name='name_filter',
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='filters',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
