# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0012_auto_20160827_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalistquery',
            old_name='model_values',
            new_name='values',
        ),
    ]
