# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0013_auto_20160827_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
