# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0014_datalistquery_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalistquery',
            name='module_name',
        ),
    ]
