# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0015_remove_datalistquery_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
