# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0016_datalistquery_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalistquery',
            name='module_name',
            field=models.CharField(max_length=100),
        ),
    ]
