# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-07 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0017_auto_20160827_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datalistquery',
            name='filters',
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='and_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='or_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datalistquery',
            name='values',
            field=models.CharField(max_length=1024),
        ),
    ]
