# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-05 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0018_auto_20161207_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='gateway_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='institution_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
