# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-06 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0019_auto_20170205_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='order',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
