# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0020_datalistquery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='count',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
