# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0021_datalistquery_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
