# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0022_datalistquery_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='date_time_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='date_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
