# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0023_auto_20170424_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='links',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
