# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-24 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0024_datalistquery_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalistquery',
            old_name='count',
            new_name='count_values',
        ),
    ]
