# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-11 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0026_auto_20170424_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='list_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
