# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0029_auto_20170519_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='sum_values',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
