# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0030_datalistquery_sum_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='not_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
