# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-21 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0031_datalistquery_not_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='data_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='last_balance',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datalistquery',
            name='count_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datalistquery',
            name='sum_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
