# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-26 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0032_auto_20170521_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='gateway_profile_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
