# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0033_datalistquery_gateway_profile_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='month_year_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
