# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0034_datalistquery_month_year_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='avg_values',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
