# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0035_datalistquery_avg_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='date_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datalistquery',
            name='time_filters',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
