# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0037_imagelist_imagelisttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelist',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='imagelist',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='imagelist',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='imagelist',
            name='institution',
        ),
        migrations.DeleteModel(
            name='ImageList',
        ),
    ]
