# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0024_auto_20170519_1205'),
        ('administration', '0017_auto_20170614_1816'),
        ('dsc', '0038_auto_20170616_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('image', models.ImageField(max_length=200, upload_to=b'dsc_imagelist_image/')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('channel', models.ManyToManyField(blank=True, to='administration.Channel')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('image_list_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsc.ImageListType')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
            ],
        ),
    ]
