# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0039_imagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
