# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0040_auto_20170616_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='pn',
            field=models.BooleanField(default=False, help_text=b'Push Notification', verbose_name=b'Push Notification'),
        ),
        migrations.AddField(
            model_name='datalist',
            name='pn_id_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Push Notification ID Field'),
        ),
    ]
