# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0042_auto_20170623_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistquery',
            name='token_filter',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
