# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigator',
            old_name='session',
            new_name='session_hop',
        ),
    ]
