# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0002_auto_20171008_2125'),
        ('vcs', '0002_auto_20171008_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigator',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Session'),
        ),
    ]
