# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0003_navigator_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigator',
            name='session_hop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcs.SessionHop'),
        ),
    ]
