# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0006_menuitem_enrollment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='enrollment_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='enrollment_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
