# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20171014_1214'),
        ('vcs', '0007_auto_20171020_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='enrollment_type',
            new_name='enrollment_type_included',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='enrollment_type',
            new_name='enrollment_type_included',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='enrollment_excluded',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='enrollment_excluded',
        ),
        migrations.AddField(
            model_name='menu',
            name='enrollment_type_excluded',
            field=models.ManyToManyField(blank=True, related_name='menu_enrollment_type_excluded', to='crm.EnrollmentType'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='enrollment_type_excluded',
            field=models.ManyToManyField(blank=True, related_name='menuitem_enrollment_type_excluded', to='crm.EnrollmentType'),
        ),
    ]
