# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=1200)),
                ('description', models.CharField(max_length=100)),
                ('expiry_date', models.DateTimeField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Country')),
            ],
        ),
    ]
