# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0002_auto_20171008_2125'),
        ('crm', '0005_auto_20170708_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Profile'),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Profile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gateway_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
        ),
    ]
