# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171014_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='gateway_profile',
        ),
        migrations.RemoveField(
            model_name='paymentoption',
            name='gateway_profile',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Profile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='record',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentoption',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Profile'),
        ),
    ]
