# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='pn_update_field',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Push Update Field'),
        ),
    ]
