# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0002_datalist_pn_update_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='pn_action',
            field=models.CharField(blank=True, help_text=b'replace|append|compare', max_length=50, null=True, verbose_name=b'Push Action'),
        ),
    ]
