# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0004_auto_20170708_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='pn_action',
            field=models.ManyToManyField(blank=True, to='dsc.PushAction'),
        ),
    ]
