# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('bill_to_forename', models.CharField(max_length=30)),
                ('bill_to_surname', models.CharField(max_length=30)),
                ('bill_to_email', models.CharField(max_length=30)),
                ('bill_to_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('bill_to_address_line1', models.CharField(max_length=30)),
                ('bill_to_address_city', models.CharField(max_length=30)),
                ('bill_to_address_state', models.CharField(blank=True, max_length=30, null=True)),
                ('bill_to_address_country', models.CharField(max_length=30)),
                ('bill_to_address_postal_code', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=30)),
                ('card_expiry_date', models.CharField(max_length=30)),
                ('payment_token', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CardRecordStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardTypeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardtype',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardTypeStatus'),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardType'),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardRecordStatus'),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
