# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0010_auto_20160603_0751'),
        ('upc', '0004_auto_20160528_0459'),
        ('crc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrecord',
            old_name='bill_to_forename',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='cardrecord',
            old_name='bill_to_surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='gateway_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='remittance_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paygate.RemittanceProduct'),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='response',
            field=models.CharField(blank=True, max_length=1920, null=True),
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='cybersource_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='bill_to_address_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='bill_to_address_country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='bill_to_address_postal_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='bill_to_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='card_expiry_date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='payment_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
