# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0002_auto_20160612_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrecord',
            name='gateway_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='remittance_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.RemittanceProduct'),
        ),
    ]
