# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0003_auto_20160612_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrecord',
            name='user',
        ),
    ]
