# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0015_auto_20170310_0355'),
        ('bridge', '0006_transaction_fingerprint'),
        ('administration', '0012_auto_20170306_1741'),
        ('crc', '0004_remove_cardrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRecordActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('request', models.CharField(max_length=12800)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=19)),
                ('raise_charges', models.NullBooleanField(default=False)),
                ('response', models.CharField(blank=True, max_length=12800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardRecordActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='cardrecord',
            old_name='payment_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='cardtype',
            old_name='cybersource_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_address_city',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_address_country',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_address_line1',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_address_postal_code',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_address_state',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_email',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='bill_to_phone',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='remittance_product',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='response',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='cardrecord',
            name='pan',
            field=models.CharField(default=b'411111xxxxxx1111', max_length=512),
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='card_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardRecord'),
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='response_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus'),
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='transaction_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.TransactionStatus'),
        ),
    ]
