# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0005_auto_20170328_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrecordactivity',
            name='reference',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
