# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0006_auto_20170401_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='card_record',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='transaction_status',
        ),
        migrations.DeleteModel(
            name='CardRecordActivity',
        ),
    ]
