# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_transaction_fingerprint'),
        ('pos', '0003_cartitem_channel'),
        ('administration', '0012_auto_20170306_1741'),
        ('upc', '0016_auto_20170330_0814'),
        ('crc', '0007_auto_20170401_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRecordActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('request', models.CharField(max_length=12800)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=19)),
                ('raise_charges', models.NullBooleanField(default=False)),
                ('response', models.CharField(blank=True, max_length=12800, null=True)),
                ('card_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardRecord')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.PurchaseOrder')),
                ('response_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus')),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.TransactionStatus')),
            ],
        ),
    ]
