# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0009_auto_20170607_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardRecordActivityStatus',
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='scheduled_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardrecordactivity',
            name='sends',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
