# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_auto_20170614_1816'),
        ('crc', '0010_auto_20170607_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardVerificationAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
            ],
        ),
    ]
