# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0011_cardverificationamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrecord',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='gateway_profile',
        ),
        migrations.RemoveField(
            model_name='cardrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='card_record',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='cardrecordactivity',
            name='transaction_status',
        ),
        migrations.DeleteModel(
            name='CardRecord',
        ),
        migrations.DeleteModel(
            name='CardRecordActivity',
        ),
    ]
