# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0024_auto_20170519_1205'),
        ('pos', '0006_salecharge_per_item'),
        ('bridge', '0010_transaction_csrf_token'),
        ('administration', '0017_auto_20170614_1816'),
        ('crc', '0012_auto_20170616_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('card_number', models.CharField(max_length=30)),
                ('card_expiry_date', models.DateField(max_length=30)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('pan', models.CharField(default=b'411111xxxxxx1111', max_length=512)),
                ('activation_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('activation_pin', models.CharField(blank=True, max_length=200, null=True)),
                ('pin_retries', models.SmallIntegerField(default=0, help_text=b'Max PIN retries=3 then locks record')),
                ('activation_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardType')),
                ('gateway_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardRecordStatus')),
            ],
        ),
        migrations.CreateModel(
            name='CardRecordActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('request', models.CharField(max_length=12800)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=19)),
                ('raise_charges', models.NullBooleanField(default=False)),
                ('response', models.CharField(blank=True, max_length=12800, null=True)),
                ('scheduled_send', models.DateTimeField(blank=True, null=True)),
                ('sends', models.IntegerField()),
                ('card_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crc.CardRecord')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.PurchaseOrder')),
                ('response_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus')),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.TransactionStatus')),
            ],
        ),
    ]
