# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crc', '0013_cardrecord_cardrecordactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrecord',
            name='is_default',
            field=models.NullBooleanField(default=False),
        ),
    ]
