# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170917_0819'),
        ('upc', '0001_initial'),
        ('crm', '0005_auto_20170708_1642'),
        ('bridge', '0008_auto_20170917_0715'),
        ('crb', '0002_auto_20170921_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('forename_1', models.CharField(blank=True, max_length=30, null=True)),
                ('forename_2', models.CharField(blank=True, max_length=30, null=True)),
                ('forename_3', models.CharField(blank=True, max_length=30, null=True)),
                ('salutation', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('client_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('gateway_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Gender')),
                ('identification_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crb.IdentificationProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem')),
                ('report_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crb.ReportReason')),
                ('report_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crb.ReportSector')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Service')),
            ],
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='reference_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crb.ReferenceType'),
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='response_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus'),
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crb.ReferenceActivityStatus'),
        ),
    ]
