# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170917_0819'),
        ('crb', '0003_auto_20170921_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('forename_1', models.CharField(blank=True, max_length=30, null=True)),
                ('forename_2', models.CharField(blank=True, max_length=30, null=True)),
                ('forename_3', models.CharField(blank=True, max_length=30, null=True)),
                ('salutation', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('client_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Gender')),
                ('identification_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crb.IdentificationProfile')),
            ],
        ),
        migrations.RenameModel(
            old_name='ReferenceType',
            new_name='ReferenceActivityType',
        ),
        migrations.RenameField(
            model_name='referenceactivity',
            old_name='reference_type',
            new_name='reference_activity_type',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='client_number',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='forename_1',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='forename_2',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='forename_3',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='salutation',
        ),
        migrations.RemoveField(
            model_name='referenceactivity',
            name='surname',
        ),
    ]
