# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170917_0819'),
        ('upc', '0001_initial'),
        ('crb', '0005_auto_20170921_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceactivity',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='gateway',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='request',
            field=models.CharField(default=b'{}', max_length=1920),
        ),
        migrations.AddField(
            model_name='referenceactivity',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='referenceactivitytype',
            name='details',
            field=models.CharField(default=b'{}', max_length=1920),
        ),
    ]
