# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crb', '0006_auto_20170921_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='account_list',
            field=models.CharField(blank=True, max_length=1920, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='account_summary',
            field=models.CharField(blank=True, max_length=1920, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='credit_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='credit_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crb.CreditGrade'),
        ),
    ]
