# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20170917_0819'),
        ('upc', '0001_initial'),
        ('crb', '0007_auto_20171001_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('min_credit_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('min_credit_score', models.IntegerField(blank=True, null=True)),
                ('base_initial_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('lend_to_defaulters', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('min_credit_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crb.CreditGrade')),
            ],
        ),
    ]
