# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crb', '0010_referenceaccountstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceaccountstatus',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
