# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crb', '0011_auto_20171001_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceaccountstatus',
            name='defaulted',
            field=models.BooleanField(default=False),
        ),
    ]
