# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crb', '0012_referenceaccountstatus_defaulted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='account_list',
            new_name='credit_account_list',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='account_summary',
            new_name='credit_account_summary',
        ),
    ]
