# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.NullBooleanField(default=False)),
                ('min_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('max_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('account_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionTill')),
            ],
        ),
        migrations.CreateModel(
            name='AccountCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('charge_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('is_percentage', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('credit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
                ('transaction_reference', models.CharField(blank=True, max_length=45, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_bf', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dest_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_account', to='vbs.Account')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('credit_acc', models.BooleanField(default=False)),
                ('min_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('max_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('loan_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('loan_time', models.IntegerField(blank=True, help_text=b'In Days', null=True)),
                ('saving_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('saving_time', models.IntegerField(blank=True, help_text=b'In Days', null=True)),
                ('description', models.CharField(max_length=100)),
                ('allowed_currency', models.ManyToManyField(blank=True, to='administration.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType'),
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.TransactionType'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountStatus'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account__created_by', to='upc.GatewayProfile'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='gateway_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
        ),
    ]
