# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0002_auto_20160424_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='compound_interest',
            field=models.BooleanField(default=False),
        ),
    ]
