# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-30 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0003_accounttype_compound_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='credit_acc',
            new_name='deposit_taking',
        ),
    ]
