# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0004_auto_20160430_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='max_credit_limit',
            new_name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='min_credit_limit',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='daily_withdrawal_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
