# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('vbs', '0005_auto_20160619_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='allowed_currency',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
            preserve_default=False,
        ),
    ]
