# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0006_auto_20160620_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
