# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0007_auto_20160626_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='accountcharge',
            name='currency',
        ),
    ]
