# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_enrollment_date_of_enrollment'),
        ('vbs', '0009_remove_account_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem'),
        ),
    ]
