# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0010_accounttype_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
