# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0011_account_credit_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='credit_due_date',
        ),
    ]
