# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0012_remove_account_credit_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='product_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem'),
            preserve_default=False,
        ),
    ]
