# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0006_gatewayprofile_pin_retries'),
        ('bridge', '0003_auto_20160627_0700'),
        ('administration', '0002_mno_mnoprefix'),
        ('vbs', '0013_auto_20160629_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcharge',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
        migrations.RemoveField(
            model_name='accountcharge',
            name='gateway',
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='administration.Gateway'),
        ),
        migrations.RemoveField(
            model_name='accountcharge',
            name='institution',
        ),
        migrations.AddField(
            model_name='accountcharge',
            name='institution',
            field=models.ManyToManyField(blank=True, to='upc.Institution'),
        ),
    ]
