# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0014_auto_20160701_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcharge',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='accountcharge',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='accountcharge',
            name='transaction_type',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
