# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0015_auto_20160701_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ManyToManyField(to='vbs.AccountType'),
        ),
    ]
