# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0016_auto_20160703_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType'),
            preserve_default=False,
        ),
    ]
