# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0017_accountmanager_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmanager',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType'),
        ),
    ]
