# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_mno_mnoprefix'),
        ('vbs', '0018_auto_20160703_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit_currency',
            field=models.ForeignKey(default=74, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
            preserve_default=False,
        ),
    ]
