# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0020_auto_20160704_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit_limit_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
        ),
    ]
