# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0021_auto_20160704_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='institution',
        ),
    ]
