# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20160627_0700'),
        ('vbs', '0023_accountmanager_credit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcharge',
            name='service',
            field=models.ManyToManyField(blank=True, to='bridge.Service'),
        ),
    ]
