# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0024_accountcharge_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('interest_time', models.IntegerField(blank=True, help_text=b'In Days', null=True)),
                ('min_time', models.IntegerField(blank=True, help_text=b'In Days', null=True)),
                ('max_time', models.IntegerField(blank=True, help_text=b'In Days', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='credit_time',
            field=models.IntegerField(blank=True, help_text=b'In Days', null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='credit_type',
            field=models.ManyToManyField(blank=True, to='vbs.CreditType'),
        ),
    ]
