# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_paymentmethod_channel'),
        ('vbs', '0025_auto_20170122_0817'),
    ]

    operations = [
    ]
