# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_paymentmethod_channel'),
        ('vbs', '0026_auto_20170122_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditOverdue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('overdue_time', models.IntegerField(blank=True, help_text=b'In Days', null=True)),
                ('notification_details', models.CharField(max_length=1920)),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.CreditType')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Service')),
            ],
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='credit_overdue',
            field=models.ManyToManyField(blank=True, to='vbs.CreditOverdue'),
        ),
    ]
