# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0028_auto_20170123_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmanager',
            name='credit_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
