# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0030_creditoverduestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditoverdue',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vbs.CreditOverdueStatus'),
            preserve_default=False,
        ),
    ]
