# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-25 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0031_creditoverdue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditoverdue',
            name='name',
        ),
    ]
