# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_producttype_institution_till'),
        ('vbs', '0033_creditoverdue_product_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('limit_review_rate', models.DecimalField(decimal_places=2, max_digits=19)),
                ('product_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('share_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_bf', models.DecimalField(decimal_places=2, max_digits=19)),
                ('processed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.Account')),
                ('investment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vbs.InvestmentAccountType')),
            ],
        ),
    ]
