# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0034_investmentaccounttype_investmentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='f_account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_account_type', to='vbs.AccountType'),
            preserve_default=False,
        ),
    ]
