# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0035_account_f_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='f_account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vbs.AccountType'),
        ),
    ]
