# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('vbs', '0036_auto_20170303_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='f_gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_gateway', to='administration.Gateway'),
            preserve_default=False,
        ),
    ]
