# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('vbs', '0037_accounttype_f_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='f_gateway',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='gateway',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
    ]
