# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('vbs', '0038_auto_20170303_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccounttype',
            name='gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
    ]
