# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0039_investmentaccounttype_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccounttype',
            name='limit_review_rate',
        ),
        migrations.AddField(
            model_name='investmentaccounttype',
            name='investment_loan_allowed',
            field=models.DecimalField(decimal_places=2, default=0, help_text=b'In Percentage', max_digits=19),
            preserve_default=False,
        ),
    ]
