# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0040_auto_20170305_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='product_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem'),
        ),
    ]
