# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0042_accounttype_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmanager',
            name='account_type',
        ),
    ]
