# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muziqbit', '0002_music_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image_path',
        ),
    ]
