# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-07 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pn',
            field=models.BooleanField(default=False, help_text=b'Push Notification', verbose_name=b'Push Notification'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pn_ack',
            field=models.BooleanField(default=False, help_text=b'Push Notification Acknowledged', verbose_name=b'Push Notification Acknowledged'),
        ),
    ]
