# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(max_length=45),
        ),
    ]
