# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_transaction_fingerprint'),
        ('pos', '0003_cartitem_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmanager',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.PaymentMethod'),
        ),
    ]
