# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0024_auto_20170519_1205'),
        ('administration', '0016_forex'),
        ('bridge', '0009_servicecommand_profile_status'),
        ('crm', '0017_auto_20170601_2003'),
        ('pos', '0004_billmanager_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('charge_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('is_percentage', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
                ('payment_method', models.ManyToManyField(blank=True, to='bridge.PaymentMethod')),
                ('product_type', models.ManyToManyField(blank=True, to='crm.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='SaleChargeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem')),
            ],
        ),
        migrations.AddField(
            model_name='salecharge',
            name='sale_charge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.SaleChargeType'),
        ),
    ]
