# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-03 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20170603_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecharge',
            name='per_item',
            field=models.BooleanField(default=False),
        ),
    ]
