# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_salecharge_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmanager',
            name='pn',
            field=models.BooleanField(default=False, help_text=b'Push Notification', verbose_name=b'Push Notification'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pn',
            field=models.BooleanField(default=False, help_text=b'Push Notification', verbose_name=b'Push Notification'),
        ),
    ]
