# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20170623_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmanager',
            name='pn_ack',
            field=models.BooleanField(default=False, help_text=b'Push Notification Acknowledged', verbose_name=b'Push Notification Acknowledged'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pn_ack',
            field=models.BooleanField(default=False, help_text=b'Push Notification Acknowledged', verbose_name=b'Push Notification Acknowledged'),
        ),
    ]
