# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-02 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionincomingservice',
            name='institution',
        ),
    ]
