# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='on_sale',
            new_name='variable_unit',
        ),
    ]
