# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='account_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
