# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-06 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_paymentoption_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentoption',
            name='account_type',
        ),
    ]
