# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_enrollment_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image_path',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'muziqbit_image_path/'),
        ),
    ]
