# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170708_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='default_product',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'crm_productitem_productpath/'),
        ),
        migrations.AlterField(
            model_name='itemextra',
            name='product_path',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'crm_productitem_productpath/'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='default_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=b'crm_productitem_imagepath/'),
        ),
    ]
