# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_productitem_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='image_path',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'crm_productitem_imagepath/'),
        ),
    ]
