# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160528_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date_of_enrollment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
