# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20160627_0700'),
        ('crm', '0007_auto_20160704_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharge',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
    ]
