# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0013_auto_20170101_1749'),
        ('crm', '0008_productcharge_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='institution_till',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionTill'),
        ),
    ]
