# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0014_auto_20170306_1741'),
        ('crm', '0009_producttype_institution_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='f_gateway_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_gateway_profile', to='upc.GatewayProfile'),
        ),
    ]
