# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-07 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_enrollment_f_gateway_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='gateway_profile',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='f_gateway_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile'),
        ),
    ]
