# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-07 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170307_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='f_gateway_profile',
            new_name='gateway_profile',
        ),
    ]
