# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_enrollmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.EnrollmentType'),
        ),
    ]
