# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-26 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0024_auto_20170519_1205'),
        ('bridge', '0009_servicecommand_profile_status'),
        ('crm', '0015_auto_20170418_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('account_alias', models.CharField(blank=True, max_length=200, null=True)),
                ('account_record', models.CharField(max_length=50)),
                ('gateway_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOptionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PaymentOptionStatus'),
        ),
    ]
