# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20170526_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmenttype',
            name='institution',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.EnrollmentType'),
        ),
        migrations.AlterField(
            model_name='enrollmenttype',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem'),
        ),
    ]
