# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_productdisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_display',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.ProductDisplay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productitem',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
    ]
