# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20170613_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
