# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
        ('crm', '0001_initial'),
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('request', models.CharField(blank=True, max_length=1920, null=True)),
                ('url', models.CharField(max_length=640)),
                ('account_id', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloatManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ext_outbound_id', models.CharField(blank=True, max_length=200, null=True)),
                ('credit', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_bf', models.DecimalField(decimal_places=2, max_digits=19)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('request', models.CharField(max_length=3840)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('message', models.CharField(blank=True, max_length=1920, null=True)),
                ('ext_inbound_id', models.CharField(blank=True, max_length=200, null=True)),
                ('inst_notified', models.NullBooleanField(default=False)),
                ('inst_num_tries', models.IntegerField(blank=True, null=True)),
                ('product_processed', models.NullBooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
                ('gateway_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('request', models.CharField(max_length=3840)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('scheduled_send', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1920, null=True)),
                ('sends', models.IntegerField()),
                ('ext_outbound_id', models.CharField(blank=True, max_length=200, null=True)),
                ('inst_notified', models.NullBooleanField(default=False)),
                ('inst_num_tries', models.IntegerField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Poller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('request', models.CharField(max_length=1920)),
                ('url', models.CharField(max_length=640)),
                ('account_id', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PollerFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('ext_service_id', models.CharField(max_length=250)),
                ('ext_service_username', models.CharField(blank=True, help_text=b'Optional', max_length=320, null=True)),
                ('ext_service_password', models.CharField(blank=True, help_text=b'Optional', max_length=320, null=True)),
                ('ext_service_details', models.CharField(blank=True, max_length=1920, null=True)),
                ('institution_till_url', models.CharField(blank=True, max_length=640, null=True)),
                ('institution_till_username', models.CharField(blank=True, help_text=b'Optional', max_length=320, null=True)),
                ('institution_till_password', models.CharField(blank=True, help_text=b'Optional', max_length=320, null=True)),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution_till', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionTill')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Service')),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('ext_product_id', models.CharField(blank=True, max_length=250, null=True)),
                ('realtime', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paygate.Endpoint')),
                ('payment_method', models.ManyToManyField(blank=True, to='bridge.PaymentMethod')),
                ('product_type', models.ManyToManyField(blank=True, to='crm.ProductType')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.Remittance')),
                ('service', models.ManyToManyField(blank=True, to='bridge.Service')),
            ],
        ),
        migrations.CreateModel(
            name='RemittanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='remittance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.RemittanceStatus'),
        ),
        migrations.AddField(
            model_name='poller',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.PollerFrequency'),
        ),
        migrations.AddField(
            model_name='poller',
            name='remittance_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.RemittanceProduct'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='remittance_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.RemittanceProduct'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='response_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paygate.OutgoingState'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='remittance_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.RemittanceProduct'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='response_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.ResponseStatus'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paygate.IncomingState'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='till',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionTill'),
        ),
    ]
