# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
        ('paygate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='product_type',
        ),
        migrations.AddField(
            model_name='incoming',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Service'),
        ),
    ]
