# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0002_auto_20160226_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incoming',
            old_name='product_processed',
            new_name='processed',
        ),
    ]
