# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0002_auto_20160226_0509'),
        ('bridge', '0001_initial'),
        ('paygate', '0003_auto_20160226_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionIncomingService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.Service')),
            ],
        ),
    ]
