# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0004_institutionincomingservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='till',
        ),
    ]
