# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vbs', '0001_initial'),
        ('paygate', '0005_remove_incoming_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionincomingservice',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vbs.Account'),
        ),
    ]
