# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160420_0415'),
        ('paygate', '0007_auto_20160226_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionincomingservice',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionincomingservice',
            name='keyword',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institutionincomingservice',
            name='product_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem'),
        ),
    ]
