# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0008_auto_20160420_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionincomingservice',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
    ]
