# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0009_auto_20160421_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floatmanager',
            old_name='amount',
            new_name='float_amount',
        ),
    ]
