# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('paygate', '0011_auto_20160612_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittanceproduct',
            name='currency',
            field=models.ManyToManyField(blank=True, to='administration.Currency'),
        ),
    ]
