# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_productcharge_payment_method'),
        ('upc', '0006_gatewayprofile_pin_retries'),
        ('bridge', '0003_auto_20160627_0700'),
        ('administration', '0002_mno_mnoprefix'),
        ('paygate', '0012_remittanceproduct_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('credit', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('charge_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('is_percentage', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('for_float', models.NullBooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='FloatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem')),
                ('product_type', models.ManyToManyField(blank=True, to='crm.ProductType')),
                ('service', models.ManyToManyField(blank=True, to='bridge.Service')),
            ],
        ),
        migrations.AddField(
            model_name='floatcharge',
            name='float_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paygate.FloatType'),
        ),
        migrations.AddField(
            model_name='floatcharge',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='floatcharge',
            name='till',
            field=models.ManyToManyField(blank=True, to='upc.InstitutionTill'),
        ),
        migrations.AddField(
            model_name='floatmanager',
            name='float_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paygate.FloatType'),
        ),
    ]
