# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0013_auto_20160705_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatmanager',
            name='product_item',
        ),
        migrations.AlterField(
            model_name='floatmanager',
            name='float_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='paygate.FloatType'),
            preserve_default=False,
        ),
    ]
