# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20160627_0700'),
        ('paygate', '0014_auto_20160706_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatcharge',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='floatcharge',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='floatcharge',
            name='till',
        ),
        migrations.AddField(
            model_name='floattype',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
    ]
