# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0015_auto_20160706_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatcharge',
            name='for_float',
        ),
    ]
