# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_auto_20160627_0700'),
        ('paygate', '0016_remove_floatcharge_for_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatcharge',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
    ]
