# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0018_incoming_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittanceproduct',
            name='show_message',
            field=models.BooleanField(default=False),
        ),
    ]
