# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0013_auto_20170101_1749'),
        ('paygate', '0021_auto_20170115_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatcharge',
            name='institution',
            field=models.ManyToManyField(blank=True, to='upc.Institution'),
        ),
    ]
