# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-20 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0022_floatcharge_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floatmanager',
            old_name='institution',
            new_name='f_institution',
        ),
    ]
