# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('upc', '0013_auto_20170101_1749'),
        ('paygate', '0023_auto_20170220_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatmanager',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='administration.Gateway'),
        ),
        migrations.AddField(
            model_name='floatmanager',
            name='institution',
            field=models.ManyToManyField(blank=True, to='upc.Institution'),
        ),
        migrations.AlterField(
            model_name='floatmanager',
            name='f_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_insitution', to='upc.Institution'),
        ),
    ]
