# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('paygate', '0025_auto_20170220_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatcharge',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='administration.Gateway'),
        ),
    ]
