# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0026_floatcharge_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='gateway',
            field=models.ManyToManyField(to='administration.Gateway'),
        ),
    ]
