# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('paygate', '0027_auto_20170220_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatmanager',
            name='f_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
        ),
        migrations.AlterField(
            model_name='floatmanager',
            name='gateway',
            field=models.ManyToManyField(blank=True, related_name='gateway_list', to='administration.Gateway'),
        ),
    ]
