# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0028_auto_20170221_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatmanager',
            name='f_institution',
        ),
        migrations.RemoveField(
            model_name='floatmanager',
            name='gateway',
        ),
        migrations.AlterField(
            model_name='floatmanager',
            name='f_gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
    ]
