# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0029_auto_20170221_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floatmanager',
            old_name='f_gateway',
            new_name='gateway',
        ),
    ]
