# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0030_auto_20170221_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='gateway',
            field=models.ManyToManyField(blank=True, to='administration.Gateway'),
        ),
    ]
