# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0013_auto_20170101_1749'),
        ('paygate', '0031_auto_20170221_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatmanager',
            name='f_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AlterField(
            model_name='floatmanager',
            name='institution',
            field=models.ManyToManyField(blank=True, related_name='float_manager_institution', to='upc.Institution'),
        ),
    ]
