# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0032_auto_20170223_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatmanager',
            name='institution',
        ),
    ]
