# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0033_remove_floatmanager_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floatmanager',
            old_name='f_institution',
            new_name='institution',
        ),
    ]
