# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_producttype_institution_till'),
        ('paygate', '0034_auto_20170223_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floattype',
            name='product_item',
        ),
        migrations.AddField(
            model_name='floattype',
            name='float_product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='float_product_type', to='crm.ProductType'),
        ),
    ]
