# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-04 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('paygate', '0035_auto_20170301_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionincomingservice',
            name='gl_account',
        ),
        migrations.RemoveField(
            model_name='institutionincomingservice',
            name='is_default',
        ),
        migrations.AddField(
            model_name='institutionincomingservice',
            name='gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institutionincomingservice',
            name='keyword',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
