# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paygate', '0036_auto_20170304_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='gateway_profile',
        ),
        migrations.AlterField(
            model_name='institutionincomingservice',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductItem'),
        ),
    ]
