# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-22 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0015_auto_20170310_0355'),
        ('paygate', '0037_auto_20170304_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
    ]
