# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-18 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikobizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='ssl_certificate',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='ssl_certificate_ca',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='ssl_certificate_key',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
    ]
