# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikobizz', '0002_auto_20170619_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='ssl_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ssl_certificate_ca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ssl_certificate_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
