# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0008_auto_20170917_0715'),
        ('notify', '0002_auto_20170719_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='trigger',
            field=models.ManyToManyField(blank=True, to='bridge.Trigger'),
        ),
    ]
