# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notificationtemplate_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='recipient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
