# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-07 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_paymentmethod_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='csrf_token',
            new_name='token',
        ),
    ]
