# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0001_initial'),
        ('administration', '0001_initial'),
        ('bridge', '0003_auto_20170707_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('access_level', models.ManyToManyField(blank=True, to='administration.AccessLevel')),
                ('activity_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_serice', to='bridge.Service')),
                ('gateway', models.ManyToManyField(blank=True, to='administration.Gateway')),
                ('institution', models.ManyToManyField(blank=True, to='upc.Institution')),
                ('trigger_service', models.ManyToManyField(to='bridge.Service')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundServiceActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=1920)),
                ('background_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.BackgroundService')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Channel')),
                ('gateway_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.BackgroundServiceStatus'),
        ),
    ]
