# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_auto_20170719_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundserviceactivity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridge.TransactionStatus'),
        ),
        migrations.DeleteModel(
            name='BackgroundServiceStatus',
        ),
    ]
