# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_auto_20170916_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
