# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0001_initial'),
        ('administration', '0001_initial'),
        ('bridge', '0007_backgroundserviceactivity_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Currency'),
        ),
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='gateway',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backgroundserviceactivity',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
    ]
