# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-06 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crb', '0002_identificationdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentificationDocument',
            new_name='Identification',
        ),
    ]
