# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-08 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crb', '0003_auto_20170606_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('sector_code', models.IntegerField()),
            ],
        ),
    ]
