# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('validate_min', models.CharField(max_length=45)),
                ('validate_max', models.CharField(max_length=45)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('page_string', models.CharField(max_length=320)),
                ('submit', models.BooleanField(default=False)),
                ('level', models.IntegerField()),
                ('group_select', models.IntegerField(blank=True, null=True)),
                ('selection_preview', models.BooleanField(default=False)),
                ('menu_description', models.CharField(max_length=50)),
                ('access_level', models.ManyToManyField(to='administration.AccessLevel')),
                ('code', models.ManyToManyField(to='vcs.Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('input_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.InputVariable')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.CharField(max_length=200)),
                ('item_level', models.IntegerField()),
                ('access_level', models.ManyToManyField(to='administration.AccessLevel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Country')),
            ],
        ),
        migrations.CreateModel(
            name='MNOPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('mno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.MNO')),
            ],
        ),
        migrations.CreateModel(
            name='Navigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item_list', models.CharField(blank=True, max_length=1024, null=True)),
                ('nav_step', models.IntegerField(blank=True, null=True)),
                ('input_select', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.Code')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcs.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='SessionHop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_tries', models.IntegerField(blank=True, null=True)),
                ('num_of_sends', models.IntegerField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Channel')),
                ('gateway_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('variable', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='navigator',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.SessionHop'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.MenuStatus'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.MenuStatus'),
        ),
        migrations.AddField(
            model_name='menu',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bridge.Service'),
        ),
        migrations.AddField(
            model_name='menu',
            name='session_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.SessionState'),
        ),
        migrations.AddField(
            model_name='inputvariable',
            name='variable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.VariableType'),
        ),
        migrations.AddField(
            model_name='code',
            name='code_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.CodeType'),
        ),
        migrations.AddField(
            model_name='code',
            name='gateway',
            field=models.ManyToManyField(to='administration.Gateway'),
        ),
        migrations.AddField(
            model_name='code',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='code',
            name='mno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcs.MNO'),
        ),
    ]
