# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='created_by',
        ),
    ]
