# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0003_remove_gatewayprofile_created_by'),
        ('vcs', '0002_auto_20160321_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='profile_status',
            field=models.ManyToManyField(to='upc.ProfileStatus'),
        ),
    ]
