# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0003_menu_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='profile_status',
            field=models.ManyToManyField(blank=True, to='upc.ProfileStatus'),
        ),
    ]
