# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0003_remove_gatewayprofile_created_by'),
        ('vcs', '0004_auto_20160509_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='profile_status',
            field=models.ManyToManyField(blank=True, to='upc.ProfileStatus'),
        ),
    ]
