# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0005_menuitem_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcs.CodeType'),
        ),
        migrations.AlterField(
            model_name='code',
            name='mno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcs.MNO'),
        ),
    ]
