# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0006_auto_20160530_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mno',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcs__mno__country', to='administration.Country'),
        ),
    ]
