# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0007_auto_20160624_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mno',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mnoprefix',
            name='mno',
        ),
        migrations.AlterField(
            model_name='code',
            name='mno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.MNO'),
        ),
        migrations.DeleteModel(
            name='MNO',
        ),
        migrations.DeleteModel(
            name='MNOPrefix',
        ),
    ]
