# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0008_auto_20160624_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navigator',
            name='pin_auth',
            field=models.BooleanField(default=False),
        ),
    ]
