# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0009_auto_20160805_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
    ]
