# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0012_auto_20160917_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='alias',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
