# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0013_code_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
        ),
    ]
