# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('pin', models.CharField(blank=True, max_length=200, null=True)),
                ('access_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.AccessLevel')),
                ('allowed_host', models.ManyToManyField(blank=True, to='administration.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('business_number', models.CharField(max_length=6, unique=True)),
                ('background_image', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=140)),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to=b'upc_institution_logo/')),
                ('default_color', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('physical_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Country')),
                ('currency', models.ManyToManyField(blank=True, to='administration.Currency')),
                ('gateway', models.ManyToManyField(to='administration.Gateway')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionTill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to=b'upc_institutiontill_image/')),
                ('till_number', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, help_text=b'City/Town', max_length=200, null=True)),
                ('physical_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('details', models.CharField(blank=True, max_length=1200, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
                ('till_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='MSISDN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+\\d{9,15}$')])),
                ('is_active', models.NullBooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reset_key', models.CharField(blank=True, max_length=200, null=True)),
                ('old_password', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('api_key', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('dob', models.DateField(blank=True, null=True)),
                ('physical_addr', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to=b'upc_profile_photo/')),
                ('passport_id_number', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Country')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Gender')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TillTypeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tilltype',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.TillTypeStatus'),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.PasswordStatus'),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutiontill',
            name='till_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.TillType'),
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.InstitutionStatus'),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Profile'),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.Institution'),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='msisdn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upc.MSISDN'),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.ProfileStatus'),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
