# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='business_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
