# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-28 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0003_remove_gatewayprofile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text=b'City/Town', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_addr',
            field=models.CharField(blank=True, help_text=b'Postal Address/Postal Code', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, help_text=b'Region/State/County', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_addr',
            field=models.CharField(blank=True, help_text=b'Physical Address/Street/Location', max_length=200, null=True),
        ),
    ]
