# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0005_auto_20160614_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayprofile',
            name='pin_retries',
            field=models.SmallIntegerField(default=0, help_text=b'Max PIN retries=3 then locks profile'),
        ),
    ]
