# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20160919_1102'),
        ('upc', '0006_gatewayprofile_pin_retries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='industry',
        ),
        migrations.AddField(
            model_name='institution',
            name='industry_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.IndustryClass'),
            preserve_default=False,
        ),
    ]
