# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-02 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0009_auto_20161202_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='theme',
        ),
    ]
