# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('upc', '0010_remove_institution_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Theme'),
            preserve_default=False,
        ),
    ]
