# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_gateway_theme'),
        ('upc', '0011_institution_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='industries',
            field=models.ManyToManyField(related_name='industries', to='administration.IndustryClass'),
        ),
    ]
