# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0012_institution_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='industry_class',
        ),
        migrations.AddField(
            model_name='institution',
            name='details',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='documents',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'upc_institution_documents/'),
        ),
    ]
