# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-10 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0014_auto_20170306_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeProfileMSISDN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField()),
                ('change_pin', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upc.GatewayProfile')),
                ('msisdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.MSISDN')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeProfileMSISDNStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='changeprofilemsisdn',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.ChangeProfileMSISDNStatus'),
        ),
    ]
