# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0015_auto_20170310_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
