# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0016_auto_20170330_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postal_address',
            new_name='address',
        ),
    ]
