# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0017_auto_20170401_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passport_id_number',
            new_name='id_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
