# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-02 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0018_auto_20170402_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_number',
            new_name='national_id',
        ),
    ]
