# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0019_auto_20170402_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='msisdn',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
