# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-23 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0020_msisdn_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='msisdn',
            name='activation_device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
