# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0021_msisdn_activation_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msisdn',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='msisdn',
            name='activation_device_id',
        ),
        migrations.RemoveField(
            model_name='msisdn',
            name='device_id',
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='activation_device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gatewayprofile',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
