# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upc', '0022_auto_20170426_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayprofile',
            name='email_activation_code',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
