# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_remove_notificationtemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='template_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=b'notify_notificationtemplate_path/'),
        ),
    ]
