# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notificationtemplate_template_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('file_path', models.FileField(blank=True, max_length=200, null=True, upload_to=b'notify_templatefile_path/')),
            ],
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notify.TemplateFile'),
        ),
    ]
