# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('upc', '0003_remove_gatewayprofile_created_by'),
        ('notify', '0004_auto_20160526_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upc.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_group',
            field=models.ManyToManyField(blank=True, to='notify.ContactGroup'),
        ),
    ]
