# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20160526_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactgroup',
            name='gateway',
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
