# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20160530_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('file_path', models.FileField(blank=True, max_length=200, null=True, upload_to=b'notify_notificationattachment_path/')),
            ],
        ),
        migrations.AddField(
            model_name='inbound',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='notify.NotificationAttachment'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='notify.NotificationAttachment'),
        ),
    ]
