# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
        ('notify', '0008_auto_20160531_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='notificationproduct',
            name='payment_method',
            field=models.ManyToManyField(blank=True, to='bridge.PaymentMethod'),
        ),
    ]
