# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0009_auto_20160612_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_message',
            field=models.CharField(max_length=3840),
        ),
    ]
