# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20170306_1741'),
        ('notify', '0011_auto_20160930_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Gateway'),
        ),
    ]
